[package]
name = "image_rebuilder_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
binary_search_tree = "0.2.2"
image = "0.24.6"
outils = "0.3.0"
rand = "0.8.5"
time = "0.3.21"
